services:
  - type: web
    name: sabrs-link-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: GROUP_ID
        sync: false
      - key: ROBLOX_COOKIE
        sync: false
    autoDeploy: true
